name: CI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-n-publish:
    name: MapSyncer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.x'

        
    - name: Install build dependencies
      uses: py-actions/py-dependency-install@v4
      with: 
           update-pip: "true"
           update-setuptools: "true"
           update-wheel: "true"
           path: "requirements.txt"

    - name: Install pypa/build
      run: >-
          python -m
          pip install
          build
          --user
        
    - name: Creating dist files
      run: |
            python setup.py sdist
            python setup.py bdist_wheel --universal
      shell: bash

    - name: CheckFiles
      run: |
            ls dist
      shell: bash
    
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
